#!/usr/bin/env python3

from script_runner import run_script
import sys

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: script_run <url>")
        sys.exit(1)
    
    url = sys.argv[1]
    run_script(url)
